name: Node.js CI con Pruebas de Seguridad

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Usar Node.js 20
      uses: actions/setup-node@v1
      with:
        node-version: '20'

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar pruebas unitarias
      run: npm test

    - name: Chequeo de Seguridad de Dependencias
      run: npm audit

    # Escaneo de secretos utilizando truffleHog
    - name: Escaneo de Secretos
      run: |
        pip install truffleHog
        trufflehog --regex --entropy=True .

    # Integración de SonarCloud para análisis estático de código
    - name: Análisis Estático de Código con SonarCloud
      run: |
        npm install -g sonarqube-scanner
        sonar-scanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
